server:
  port: 8888
spring:
  datasource:
    url: jdbc:h2:D:/Data/h2/db-iokays-job3;AUTO_SERVER=TRUE;MODE=MySQL
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: h2

