server:
  port: 8888
spring:
  datasource:
    message:
      jdbc-url: jdbc:h2:tcp://localhost:9092/~/h2/db-iokays-authoriazationserver;MODE=MySQL
      driver-class-name: org.h2.Driver
    qrtz:
      url: jdbc:h2:D:/Data/h2/db-iokays-job3;AUTO_SERVER=TRUE;MODE=MySQL
      driver-class-name: org.h2.Driver