server:
  port: 8888
spring:
  datasource:
    url: jdbc:h2:D:/Data/h2/db-iokays-authoriazationserver;AUTO_SERVER=TRUE;MODE=MySQL
    driver-class-name: org.h2.Driver
    platform: h2

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

