server:
  port: 8888
spring:
  config:
    import:
      - classpath:common-config.yml
  datasource:
    platform: postgresql
    url: jdbc:postgresql://${postgresql.host}/iokays?currentSchema=test-cdewsij
    username: ${postgresql.user}
    password: ${postgresql.password}
    driver-class-name: org.postgresql.Driver
    auto-commit: true
    minimum-idle: 4
    maximum-pool-size: 8


