# Hexagonal Architecture with Java

This is a simple example of Hexagonal Architecture with Java 23.

这是一个基于Java 23 的 六边形架构与领域驱动设计的一个通用项目，并且结合现有的最新版本技术架构实现了 领域驱动设计模式和六边形架构模式组件定义.
并且结合微服务,介绍了领域层,领域事件,资源库,分布式锁,序列化,安全认证,日志等,并提供了实现功能.

== 详细介绍的章节:

https://www.iokays.com/docs/hexagonal-architecture-with-java[Hexagonal Architecture with Java 系列]

== 启动脚本:

 cd /home/ftpuser/iokays-project

 pkill -f "iokays-plugin-h2.jar"
 nohup java -jar iokays-plugin-h2.jar > h2.log 2>&1 &

 pkill -f "iokays-authorizationserver.jar"
 nohup java -jar iokays-authorizationserver.jar > authorizationserver.log 2>&1 &

 pkill -f "iokays-dispatch.jar"
 nohup java -jar iokays-dispatch.jar > quartz.log 2>&1 &

 pkill -f "iokays-flowable.jar"
 nohup java -jar iokays-flowable.jar > flowable.log 2>&1 &

 pkill -f "iokays-ai.jar"
 nohup java -jar iokays-ai.jar > ai.log 2>&1 &

 pkill -f "iokays-tools.jar"
 nohup java -jar iokays-tools.jar > tools.log 2>&1 &

== PostgreSQL数据库

=== 使用 postgres 用户连接
 sudo -u postgres psql

=== 在 PostgreSQL 中查看数据库列表
 \l, \l+ (更详细的版本)

=== 在 PostgreSQL 中查看模式列表
 \dn, \dn+ (更详细的版本)

=== 进入指定数据库
 \c iokays

=== 删除指定的模式
 DROP SCHEMA authorization_del;
 DROP SCHEMA authorization_del CASCADE;

=== 授予删除权限
 GRANT USAGE ON SCHEMA authorization_del TO postgres;

=== 将模式所有权转移给postgres用户
 ALTER SCHEMA authorization_del OWNER TO postgres;

=== 或者授予USAGE和CREATE权限（拥有者自动有删除权限）
 GRANT USAGE, CREATE ON SCHEMA authorization_del TO postgres;

=== 查找依赖关系
 SELECT * FROM pg_catalog.pg_depend
 WHERE objid = (SELECT oid FROM pg_catalog.pg_namespace WHERE nspname = 'authorization_del');



