spring:
  application:
    name: iokays-workflow-with-flowable
  datasource:
    url: jdbc:h2:D:/Data/h2/db-iokays-workflow-with-flowable;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    platform: h2

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false
  level:
    org.flowable: DEBUG

