# 该配置已经列出全部参数名, 只是有些有些私人参数的值放在了 common-config.yml 中.
server:
  port: 9999
  forward-headers-strategy: framework  # 启用头转发支持, 自动处理 X-Forwarded-Proto 头，正确地识别请求协议为 HTTPS

spring:
  application:
    name: iokays-ai
  config:
    import:
      - classpath:common-config.yml
  datasource: # 因为多数据源，所以自定义配置, 并设置为默认
    ai:
      jdbc-url: jdbc:postgresql://${postgresql.host}:5432/iokays?currentSchema=ai
      username: ${postgresql.user}
      password: ${postgresql.password}
      driver-class-name: org.postgresql.Driver
      auto-commit: true
      minimum-idle: 4
      maximum-pool-size: 8
  ai:
    chat:
      client:
        enabled: true
      memory:
        repository:
          jdbc:
            initialize-schema: always
    openai:
      api-key: "${deepseek.api-key}"
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
      # The DeepSeek API doesn't support embeddings, so we need to disable it.
      embedding:
        enabled: false
    mcp:
      client:
        enabled: true
        name: iokays-ai-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: ASYNC
        sse:
          connections:
            server1:
              url: http://localhost:1111