server:
  port: 8888
spring:
  application:
    name: iokays-authoriazationserver
  datasource:
    url: jdbc:h2:D:/Data/h2/db-iokays-authoriazationserver;AUTO_SERVER=TRUE;MODE=MySQL
    driver-class-name: org.h2.Driver
    platform: h2

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false

