CREATE TABLE LOCAL_MESSAGE  (
	MESSAGE_ID CHAR(36) NOT NULL,
	MESSAGE_SEQUENCE BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	MESSAGE_BYTES BLOB NOT NULL,
	MESSAGE_STATE INT NOT NULL,
	CREATED_DATE DATETIME(6) NOT NULL,
	UPDATED_DATE DATETIME(6) NOT NULL,
	constraint INT_MESSAGE_PK primary key (MESSAGE_ID)
) ENGINE=InnoDB;


